class Configuration:
    TASKS_NUMBER = 18
    PROCESSORS_NUMBER = 10
    TOTAL_UTILIZATION = 0.95
    TASKSETS_NUMBER = 3
    MIN_PERIOD = 1
    MAX_PERIOD = 100
    DURATION = 1000
    CYCLE_PER_MS = 1000
    NUMBER_SPORADIC_TASKS = 0
